version: '2'
services:
  web:
    image: node:latest
    volumes:
      - "./:/app"
    environment:
      - DB_HOST=db
    ports:
      - '8000:8000'
    command: bash -c "cd /app && npm start"

  db:
    image: mongo:latest

  koa:
    image: node:latest
    volumes:
      - "./:/app"
    ports:
      - '3000:3000'
    command: bash -c "cd /app && npm run koa"
